"""empty message

Revision ID: 27b92fdcd728
Revises: 
Create Date: 2022-11-03 15:28:39.579538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27b92fdcd728'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_pessoa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('nascimento', sa.Date(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(length=11), nullable=True),
    sa.Column('tipo_pessoa', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('tb_aluno',
    sa.Column('id_aluno', sa.Integer(), nullable=False),
    sa.Column('instituicaoDeEnsino', sa.String(length=80), nullable=False),
    sa.Column('curso', sa.String(length=50), nullable=False),
    sa.Column('matricula', sa.String(length=20), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pessoa_id'], ['tb_pessoa.id'], ),
    sa.PrimaryKeyConstraint('id_aluno')
    )
    op.create_table('tb_endereco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cep', sa.String(length=10), nullable=False),
    sa.Column('complemento', sa.String(length=30), nullable=False),
    sa.Column('referencia', sa.String(length=300), nullable=False),
    sa.Column('logradouro', sa.String(length=100), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pessoa_id'], ['tb_pessoa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_endereco')
    op.drop_table('tb_aluno')
    op.drop_table('tb_pessoa')
    # ### end Alembic commands ###
