"""empty message

Revision ID: 5a6b6f457657
Revises: 27b92fdcd728
Create Date: 2022-11-03 22:44:28.348591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a6b6f457657'
down_revision = '27b92fdcd728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_Rota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomeDestino', sa.String(length=30), nullable=False),
    sa.Column('qtdalunos', sa.String(length=11), nullable=False),
    sa.Column('prefeitura', sa.String(length=80), nullable=False),
    sa.Column('veiculo', sa.String(length=30), nullable=False),
    sa.Column('passageiro', sa.String(length=11), nullable=False),
    sa.Column('horaSaida', sa.String(length=80), nullable=False),
    sa.Column('horaChegada', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_uf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=90), nullable=False),
    sa.Column('sigla', sa.String(length=6), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_funcionario',
    sa.Column('id_fun', sa.Integer(), nullable=False),
    sa.Column('prefeitura', sa.String(length=90), nullable=False),
    sa.Column('cargo', sa.String(length=30), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pessoa_id'], ['tb_pessoa.id'], ),
    sa.PrimaryKeyConstraint('id_fun')
    )
    op.create_table('tb_prefeitura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomePrefeito', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('secretarios', sa.String(length=120), nullable=False),
    sa.Column('telefone', sa.String(length=120), nullable=False),
    sa.Column('rota_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rota_id'], ['tb_Rota.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nomePrefeito')
    )
    op.create_table('tb_InstituicaoDeEnsino',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.Column('telefone', sa.String(length=11), nullable=False),
    sa.Column('logradouro', sa.String(length=80), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=True),
    sa.Column('rota_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['tb_aluno.id_aluno'], ),
    sa.ForeignKeyConstraint(['rota_id'], ['tb_Rota.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_gestorApp',
    sa.Column('id_gestor', sa.Integer(), nullable=False),
    sa.Column('gestorApp', sa.String(length=80), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=True),
    sa.Column('prefeitura_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pessoa_id'], ['tb_pessoa.id'], ),
    sa.ForeignKeyConstraint(['prefeitura_id'], ['tb_prefeitura.id'], ),
    sa.PrimaryKeyConstraint('id_gestor')
    )
    op.create_table('tb_motorista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rotas', sa.String(length=80), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['funcionario_id'], ['tb_funcionario.id_fun'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_passageiro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('cidadeOrigem', sa.String(length=90), nullable=False),
    sa.Column('cidadeDestino', sa.String(length=90), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['tb_aluno.id_aluno'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_prefeito',
    sa.Column('id_prefeito', sa.Integer(), nullable=False),
    sa.Column('nomePrefeito', sa.String(length=80), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=True),
    sa.Column('prefeitura_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pessoa_id'], ['tb_pessoa.id'], ),
    sa.ForeignKeyConstraint(['prefeitura_id'], ['tb_prefeitura.id'], ),
    sa.PrimaryKeyConstraint('id_prefeito')
    )
    op.create_table('tb_veiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cidade', sa.String(length=80), nullable=False),
    sa.Column('qtdPassageiros', sa.String(length=10), nullable=False),
    sa.Column('tipoVeiculo', sa.String(length=20), nullable=False),
    sa.Column('placa', sa.String(length=20), nullable=False),
    sa.Column('motorista_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['motorista_id'], ['tb_motorista.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_veiculo')
    op.drop_table('tb_prefeito')
    op.drop_table('tb_passageiro')
    op.drop_table('tb_motorista')
    op.drop_table('tb_gestorApp')
    op.drop_table('tb_InstituicaoDeEnsino')
    op.drop_table('tb_prefeitura')
    op.drop_table('tb_funcionario')
    op.drop_table('tb_uf')
    op.drop_table('tb_Rota')
    # ### end Alembic commands ###
